### PR TITLE
Embedded scopes and interpolated ruby

### PR DESCRIPTION
**Pull request by sj26**
I hacked in support for embedded javascript, ruby, et al in HAML templates and interpolated ruby as well. :-)

### CODE REVIEW

**Comment by rafudu** [comment]
Awesome man! Just forked your version and using it as default while your commits aren't in the main version :)

**Comment by brainopia** [comment]
Nice, I hope it will be merged soon.

**Comment by ianneub** [comment]
sj26 you rock. Thanks for the tweaks. I too merged into a fork until in the master branch.

**Comment by sj26** [comment]
Going to assume this patch is never getting merged; closing.

**Pull request closed without merging**
